// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/today": {
    params: {};
  };
  "/history": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/today" | "/history";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/today.tsx": {
    id: "routes/today";
    page: "/today";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/home": typeof import("./app/routes/home.js");
  "routes/today": typeof import("./app/routes/today.js");
  "routes/history": typeof import("./app/routes/history.js");
};